### ISSUE TITLE
Some tests fail with "database is locked" error

### ISSUE THREAD

**Issue by City-busz** [TelepathyIM/telepathy-logger#5]
When I try to run the test suite included in the telepathy-logger 0.8.2 release, I get the following failure on 3 tests:
`tp-logger-FATAL-CRITICAL: _tpl_log_store_sqlite_init: Failed to drop deprecated message_cache table: database is locked
`

I attach the full log:
[test-suite.log](https://github.com/TelepathyIM/telepathy-logger/files/14012796/test-suite.log)

**Comment by City-busz** [comment]
Okay, it seems that it caused by parallel run. If I run `make -j1 check` instead of `make -j1 check`, the problem does not occur.

**Comment by apteryks** [comment]
I'd leave this open, it's still an issue.
